name: Linting

on: push

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip --version
        python -m pip install --upgrade pip==24.0 > /dev/null 2>&1 # Ignore disutils
        pip install pylint
        pip install -r ServerCode/requirements.txt
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        # Exclude specific files and suppress warning for method from pylint analysis
        pylint --max-line-length=150 --disable=W0703,E1101,E1136,R0914,R0915,W0718 $(git ls-files '*.py')
        pylint --ignore=ServerCode/mockapp/mock_ai.py,app.py --disable=R0801 $(git ls-files '*.py')
